export interface TemplateMetadata {
  id: string;
  name: string;
  description: string;
  category: "Tech" | "Luxury" | "Editorial" | "Creative" | "Minimal" | "Free";
  style: "Dark" | "Light" | "Vibrant";
  tags: string[];
  tier: "Essentiel" | "Pro" | "Premium";
  sections: number;
}

export const TEMPLATES_REGISTRY: TemplateMetadata[] = [
  {
    id: "impact-01",
    name: "NOVA Agency",
    description: "Full multi-section agency vitrine with scroll animations, magnetic buttons, portfolio carousel, and contact form.",
    category: "Creative",
    style: "Dark",
    tags: ["Agency", "Vitrine", "Multi-Section", "Animated"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-02",
    name: "Elena Korr Portfolio",
    description: "Cinematic photographer portfolio with filterable masonry gallery, fullscreen project modals, and awards section.",
    category: "Creative",
    style: "Dark",
    tags: ["Portfolio", "Photography", "Masonry", "Modal"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-03",
    name: "Maison Dorée",
    description: "Luxury e-commerce boutique with 3D tilt product cards, cart drawer, wishlist, lookbook gallery, and product detail views.",
    category: "Luxury",
    style: "Light",
    tags: ["E-commerce", "Luxury", "3D Tilt", "Cart"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-04",
    name: "L'Étoile Restaurant",
    description: "Fine dining restaurant vitrine with tabbed animated menu, reservation modal, ambiance gallery, and chef story section.",
    category: "Luxury",
    style: "Dark",
    tags: ["Restaurant", "Vitrine", "Menu", "Reservation"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-05",
    name: "NovaPlatform SaaS",
    description: "Modern SaaS landing with floating UI cards, feature grid, timeline, pricing toggle, testimonials, and conversion CTAs.",
    category: "Tech",
    style: "Dark",
    tags: ["SaaS", "Pricing", "Timeline", "Marketplace"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-06",
    name: "Fluidity",
    description: "Organic liquid-like interface with dynamic glass shapes.",
    category: "Creative",
    style: "Vibrant",
    tags: ["Fluid", "Organic", "Glassmorphism"],
    tier: "Pro",
    sections: 10,
  },
  {
    id: "impact-07",
    name: "Kinetic Mono",
    description: "Typography-driven motion with real-time cursor interactions.",
    category: "Creative",
    style: "Dark",
    tags: ["Kinetic", "Typography", "Interactive"],
    tier: "Pro",
    sections: 10,
  },
  {
    id: "impact-08",
    name: "Glass HUD Pro",
    description: "Technical data visualization with advanced glassmorphism.",
    category: "Tech",
    style: "Dark",
    tags: ["HUD", "Glassmorphism", "Data"],
    tier: "Pro",
    sections: 10,
  },
  {
    id: "impact-09",
    name: "Split Editorial",
    description: "Pinned asymmetrical layout for high-end narratives.",
    category: "Editorial",
    style: "Light",
    tags: ["Split", "Editorial", "Minimal"],
    tier: "Pro",
    sections: 10,
  },
  {
    id: "impact-10",
    name: "Typo Hero",
    description: "Pure typographic impact with massive scale transitions.",
    category: "Minimal",
    style: "Dark",
    tags: ["Typography", "Impact", "B&W"],
    tier: "Pro",
    sections: 10,
  },
  {
    id: "impact-11",
    name: "Aether Slider",
    description: "Cinematic vertical slide transitions with dynamic HUD tracking.",
    category: "Tech",
    style: "Dark",
    tags: ["Slider", "HUD", "Cinematic"],
    tier: "Pro",
    sections: 10,
  },
  {
    id: "impact-12",
    name: "Archive Index",
    description: "Interactive brutalist grid with expanding hover states.",
    category: "Minimal",
    style: "Light",
    tags: ["Grid", "Brutalist", "Portfolio"],
    tier: "Pro",
    sections: 10,
  },
  {
    id: "impact-13",
    name: "Fluid Drag",
    description: "Horizontal drag scroller with huge background indices.",
    category: "Creative",
    style: "Dark",
    tags: ["Horizontal", "Drag", "Fluid"],
    tier: "Pro",
    sections: 10,
  },
  {
    id: "impact-14",
    name: "Aethel Story",
    description: "One-page scroll story with layered scene transitions.",
    category: "Creative",
    style: "Dark",
    tags: ["One-Page", "Parallax", "Story"],
    tier: "Pro",
    sections: 10,
  },
  {
    id: "impact-15",
    name: "Ghost Shell",
    description: "E-commerce product focus with technical HUD overlays.",
    category: "Tech",
    style: "Dark",
    tags: ["E-commerce", "HUD", "Product"],
    tier: "Pro",
    sections: 10,
  },
  {
    id: "impact-16",
    name: "Silent Beams",
    description: "Cinematic atmospheric lighting with depth layering.",
    category: "Luxury",
    style: "Dark",
    tags: ["Special FX", "Nature", "Cinematic"],
    tier: "Pro",
    sections: 10,
  },
  {
    id: "impact-17",
    name: "Concrete Visions",
    description: "Minimalist masonry grid for architectural showcases.",
    category: "Minimal",
    style: "Light",
    tags: ["Portfolio", "Archive", "Grid"],
    tier: "Pro",
    sections: 10,
  },
  {
    id: "impact-18",
    name: "Fluid OS",
    description: "Expanding horizontal carousel with saturation shifts.",
    category: "Creative",
    style: "Vibrant",
    tags: ["Carousel", "Fluid", "Interactive"],
    tier: "Pro",
    sections: 10,
  },
  {
    id: "impact-19",
    name: "Aevia Agency",
    description: "Complete one-page landing layout with multiple sections.",
    category: "Creative",
    style: "Dark",
    tags: ["One-Page", "Agency", "Landing"],
    tier: "Pro",
    sections: 10,
  },
  {
    id: "impact-20",
    name: "Gold Heritage",
    description: "High-end luxury watch showcase with cinematic slider.",
    category: "Luxury",
    style: "Dark",
    tags: ["E-commerce", "Luxury", "Gold"],
    tier: "Pro",
    sections: 10,
  },
  {
    id: "impact-21",
    name: "Neo Object",
    description: "Clean editorial e-commerce layout with massive mono typography.",
    category: "Minimal",
    style: "Light",
    tags: ["E-commerce", "Minimal", "Product"],
    tier: "Pro",
    sections: 10,
  },
  {
    id: "impact-22",
    name: "Split OS",
    description: "Complex 3-column vertical sliding carousel transitions.",
    category: "Tech",
    style: "Dark",
    tags: ["Carousel", "Split", "Tech"],
    tier: "Pro",
    sections: 10,
  },
  {
    id: "impact-23",
    name: "Noir Direct",
    description: "Cinematic one-page story with B&W film aesthetics.",
    category: "Creative",
    style: "Dark",
    tags: ["One-Page", "Film Noir", "Story"],
    tier: "Pro",
    sections: 10,
  },
  {
    id: "impact-24",
    name: "Orbital Index",
    description: "Draggable circular portfolio ring with perspective-corrected rotation.",
    category: "Creative",
    style: "Dark",
    tags: ["Portfolio", "Circular", "Radial"],
    tier: "Pro",
    sections: 10,
  },
  {
    id: "impact-25",
    name: "Magnetic HUD",
    description: "3D leaning interactive dashboard with real-time cursor tracking.",
    category: "Tech",
    style: "Dark",
    tags: ["HUD", "Interactive", "3D"],
    tier: "Pro",
    sections: 10,
  },
  {
    id: "impact-26",
    name: "Glass Boutique",
    description: "Luxury e-commerce grid with heavy glassmorphism effects.",
    category: "Luxury",
    style: "Dark",
    tags: ["E-commerce", "Glass", "Shop"],
    tier: "Pro",
    sections: 10,
  },
  {
    id: "impact-27",
    name: "Perspective OS",
    description: "3D parallax carousel with depth-based transitions.",
    category: "Creative",
    style: "Dark",
    tags: ["Carousel", "3D", "Perspective"],
    tier: "Pro",
    sections: 10,
  },
  {
    id: "impact-28",
    name: "Aether Arch",
    description: "Brutalist architecture one-page story with curtain reveals.",
    category: "Minimal",
    style: "Light",
    tags: ["One-Page", "Architecture", "Minimal"],
    tier: "Pro",
    sections: 10,
  },
  {
    id: "impact-29",
    name: "Glitch Index",
    description: "Interactive portfolio grid with technical glitch hover states.",
    category: "Tech",
    style: "Dark",
    tags: ["Portfolio", "Glitch", "Grid"],
  },
  {
    id: "impact-30",
    name: "Mousetrap FX",
    description: "Interactive particle field with real-time mouse physics.",
    category: "Creative",
    style: "Dark",
    tags: ["Special FX", "Particles", "Physics"],
  },
  {
    id: "impact-31",
    name: "Lens Studio",
    description: "Fine art photography gallery with elegant framed reveals.",
    category: "Luxury",
    style: "Light",
    tags: ["Photography", "Gallery", "Minimal"],
  },
  {
    id: "impact-32",
    name: "Aevia Kitchen",
    description: "High-end gastronomy menu with fluid dish reveals.",
    category: "Luxury",
    style: "Dark",
    tags: ["Food", "Menu", "Liquid"],
  },
  {
    id: "impact-33",
    name: "Wave OS",
    description: "Quantum wavefront processing with interactive particle sine waves.",
    category: "Tech",
    style: "Dark",
    tags: ["Special FX", "Particles", "Wave"],
  },
  {
    id: "impact-34",
    name: "Horizon Estates",
    description: "Cinematic real estate showcase with technical architectural HUDs.",
    category: "Minimal",
    style: "Light",
    tags: ["Real Estate", "Architecture", "HUD"],
  },
  {
    id: "impact-35",
    name: "Flip Studio",
    description: "Editorial fashion carousel with 3D flip magazine transitions.",
    category: "Editorial",
    style: "Light",
    tags: ["Carousel", "Fashion", "3D"],
  },
  {
    id: "impact-36",
    name: "Minimal Objects",
    description: "High-contrast minimalist e-commerce showcase.",
    category: "Minimal",
    style: "Light",
    tags: ["E-commerce", "Minimal", "Product"],
  },
  {
    id: "impact-37",
    name: "Kinetic Lens",
    description: "Photography grid with scroll-linked vertical parallax.",
    category: "Creative",
    style: "Light",
    tags: ["Photography", "Gallery", "Parallax"],
  },
  {
    id: "impact-38",
    name: "Zen Kitchen",
    description: "Japanese-inspired minimalist restaurant layout.",
    category: "Minimal",
    style: "Light",
    tags: ["Food", "Minimal", "Restaurant"],
  },
  {
    id: "impact-39",
    name: "Blueprint Node",
    description: "Technical real estate visualization with architectural HUDs.",
    category: "Tech",
    style: "Dark",
    tags: ["Real Estate", "Architecture", "Tech"],
  },
  {
    id: "impact-40",
    name: "The Journey",
    description: "Immersive storytelling experience with chapter-based navigation.",
    category: "Creative",
    style: "Dark",
    tags: ["Storytelling", "One-Page", "Cinematic"],
  },
  {
    id: "impact-41",
    name: "Dynamic Live",
    description: "Real-time broadcast HUD with live data synchronisation.",
    category: "Tech",
    style: "Dark",
    tags: ["Dynamic Content", "HUD", "Live"],
  },
  {
    id: "impact-42",
    name: "Cluster OS",
    description: "Drifting asset cloud with cursor-linked depth parallax.",
    category: "Creative",
    style: "Light",
    tags: ["The Cluster", "Parallax", "Creative"],
  },
  {
    id: "impact-43",
    name: "Film Unit",
    description: "Anamorphic video hero experience with cinematic typography.",
    category: "Creative",
    style: "Dark",
    tags: ["Video", "Cinematic", "Hero"],
  },
  {
    id: "impact-44",
    name: "Neural Mesh",
    description: "Interactive network of particles with synchronized node logic.",
    category: "Tech",
    style: "Dark",
    tags: ["Particle Effects", "Tech", "Interactive"],
  },
  {
    id: "impact-45",
    name: "Shop Ring",
    description: "3D interactive product carousel with perspective-mode rotation.",
    category: "Luxury",
    style: "Dark",
    tags: ["E-commerce", "Carousel", "360"],
  },
  {
    id: "impact-46",
    name: "Glitch Hero",
    description: "Aggressive tech-focused hero with periodic glitch states.",
    category: "Tech",
    style: "Dark",
    tags: ["Hero", "Glitch", "Video"],
  },
  {
    id: "impact-47",
    name: "Tilt OS",
    description: "3D perspective carousel with leaning slide transitions.",
    category: "Creative",
    style: "Dark",
    tags: ["Carousel", "3D", "Tilt"],
  },
  {
    id: "impact-48",
    name: "Narrative OS",
    description: "Horizontal-scrolling storytelling experience.",
    category: "Creative",
    style: "Light",
    tags: ["Storytelling", "One-Page", "Horizontal"],
  },
  {
    id: "impact-49",
    name: "Leak Journal",
    description: "Fine art photography with simulated procedural light leaks.",
    category: "Luxury",
    style: "Light",
    tags: ["Photography", "Gallery", "Light Leak"],
  },
  {
    id: "impact-50",
    name: "Modern Kitchen",
    description: "High-impact brutalist restaurant menu with structured grids.",
    category: "Minimal",
    style: "Light",
    tags: ["Food", "Minimal", "Grid"],
  },
  {
    id: "impact-51",
    name: "Layered FX",
    description: "Multi-layered simulated video background with complex blend modes.",
    category: "Creative",
    style: "Dark",
    tags: ["Video", "Special FX", "Creative"],
  },
  {
    id: "impact-52",
    name: "Weather Node",
    description: "Dynamic environmental processing hero with simulated rain engine.",
    category: "Tech",
    style: "Dark",
    tags: ["Dynamic Content", "Tech", "HUD"],
  },
  {
    id: "impact-53",
    name: "Float Unit",
    description: "Interactive drifting asset grid with bobbing 3D animations.",
    category: "Creative",
    style: "Light",
    tags: ["The Cluster", "Grid", "Creative"],
  },
  {
    id: "impact-54",
    name: "Solar Drift",
    description: "Gentle golden particle field with cinematic dark mode aesthetics.",
    category: "Luxury",
    style: "Dark",
    tags: ["Particle Effects", "Luxury", "Atmospheric"],
  },
  {
    id: "impact-55",
    name: "Elastic OS",
    description: "Physical cursor interaction with multi-layered lagging physics.",
    category: "Tech",
    style: "Light",
    tags: ["Mousetrap", "Physics", "Interactive"],
  },
  {
    id: "impact-56",
    name: "Split Slider",
    description: "Cinematic vertical split transitions for high-end narratives.",
    category: "Editorial",
    style: "Dark",
    tags: ["Slider", "Split", "Editorial"],
  },
  {
    id: "impact-57",
    name: "Mask Unit",
    description: "Large-scale typography with masked background video effects.",
    category: "Creative",
    style: "Light",
    tags: ["Hero", "Masking", "Creative"],
  },
  {
    id: "impact-58",
    name: "Skew OS",
    description: "Kinetic scroll carousel with dynamic skew distortion.",
    category: "Creative",
    style: "Dark",
    tags: ["Carousel", "Kinetic", "Perspective"],
  },
  {
    id: "impact-59",
    name: "Spec 059",
    description: "Technical e-commerce showcase with interactive spec highlighting.",
    category: "Tech",
    style: "Dark",
    tags: ["E-commerce", "Interactive", "HUD"],
  },
  {
    id: "impact-60",
    name: "Stack OS",
    description: "Brutalist photography stack with sticky reveal transitions.",
    category: "Minimal",
    style: "Light",
    tags: ["Photography", "Brutalist", "Gallery"],
  },
  {
    id: "impact-61",
    name: "Segment OS",
    description: "One-page vertical dot navigation with smooth snap segments.",
    category: "Minimal",
    style: "Light",
    tags: ["One-Page", "Navigation", "Minimal"],
  },
  {
    id: "impact-62",
    name: "Liquid OS",
    description: "Visceral 'Gooey' SVG filter transitions for bold typography.",
    category: "Creative",
    style: "Dark",
    tags: ["Typography", "Special FX", "Liquid"],
  },
  {
    id: "impact-63",
    name: "Orbit Unit",
    description: "Scroll-linked luxury product rotation and scaling.",
    category: "Luxury",
    style: "Light",
    tags: ["Luxury", "Parallax", "Product"],
  },
  {
    id: "impact-64",
    name: "Data Stream OS",
    description: "Modern Matrix-inspired data rain with technical code fragments.",
    category: "Tech",
    style: "Dark",
    tags: ["Tech", "Particle Effects", "Matrix"],
  },
  {
    id: "impact-65",
    name: "Complex OS",
    description: "Complex editorial magazine grid with overlapping cinematic typography.",
    category: "Editorial",
    style: "Light",
    tags: ["Editorial", "Grid", "Magazine"],
  },
  {
    id: "impact-66",
    name: "Recipe Lab",
    description: "Interactive gastronomy protocol with ingredient anatomy.",
    category: "Luxury",
    style: "Light",
    tags: ["Food", "Interactive", "Brutalist"],
  },
  {
    id: "impact-67",
    name: "Plan 067",
    description: "HUD-inspired room switcher for high-end real estate.",
    category: "Minimal",
    style: "Dark",
    tags: ["Real Estate", "HUD", "Architecture"],
  },
  {
    id: "impact-68",
    name: "Orbit OS",
    description: "Rotating typographic path centered around a project reveal.",
    category: "Creative",
    style: "Light",
    tags: ["Creative", "Typography", "Portfolio"],
  },
  {
    id: "impact-69",
    name: "Depth OS",
    description: "Cinematic parallax depth zoom transitions for nature narratives.",
    category: "Minimal",
    style: "Dark",
    tags: ["Slider", "Parallax", "Nature"],
  },
  {
    id: "impact-70",
    name: "Crypto Node",
    description: "High-tech fintech dashboard with live data visualization.",
    category: "Tech",
    style: "Dark",
    tags: ["Dynamic Content", "Fintech", "HUD"],
  },
  {
    id: "impact-71",
    name: "Archive 35mm",
    description: "Simulated analog film grain and sprocket frame story.",
    category: "Luxury",
    style: "Dark",
    tags: ["Photography", "Film", "Nostalgic"],
  },
  {
    id: "impact-72",
    name: "Stack Unit",
    description: "3D fan-out project stack with spring physics.",
    category: "Creative",
    style: "Light",
    tags: ["Carousel", "3D", "Portfolio"],
  },
  {
    id: "impact-73",
    name: "Glitch Unit",
    description: "Aggressive cyber hero with procedural glitch effects.",
    category: "Tech",
    style: "Dark",
    tags: ["Hero", "Glitch", "Cyber"],
  },
  {
    id: "impact-74",
    name: "Aevia Kitchen",
    description: "Fine dining liquid menu with circular clip-path transitions.",
    category: "Luxury",
    style: "Light",
    tags: ["Food", "Slider", "Luxury"],
  },
  {
    id: "impact-75",
    name: "Spin Unit",
    description: "Interactive 3D product rotation for high-end e-commerce.",
    category: "Luxury",
    style: "Light",
    tags: ["E-commerce", "360", "Interactive"],
  },
  {
    id: "impact-76",
    name: "Glass OS",
    description: "Floating UI glass panels over cinematic nature backgrounds.",
    category: "Creative",
    style: "Dark",
    tags: ["Video", "Glassmorphism", "Creative"],
  },
  {
    id: "impact-77",
    name: "Tilt Grid",
    description: "Modular photography grid with 3D tilt interaction.",
    category: "Minimal",
    style: "Light",
    tags: ["Photography", "Grid", "Interactive"],
  },
  {
    id: "impact-78",
    name: "Voxel OS",
    description: "Typography composed of virtual particles with shatter animations.",
    category: "Creative",
    style: "Dark",
    tags: ["Typography", "Special FX", "Creative"],
  },
  {
    id: "impact-79",
    name: "Reveal OS",
    description: "Pinned horizontal section reveals with massive topographic anchors.",
    category: "Minimal",
    style: "Dark",
    tags: ["One-Page", "Horizontal", "Minimal"],
  },
  {
    id: "impact-80",
    name: "Lava OS",
    description: "Visceral liquid cursor trail with simulated surface tension.",
    category: "Creative",
    style: "Dark",
    tags: ["Interactive", "Liquid", "Gooey"],
  },
  {
    id: "impact-81",
    name: "Mosaic OS",
    description: "Asymmetric brutalist masonry grid with high-impact editorial styling.",
    category: "Editorial",
    style: "Light",
    tags: ["Editorial", "Grid", "Brutalist"],
  },
  {
    id: "impact-82",
    name: "Blueprint OS",
    description: "Technical mechanical diagram with data-driven interactive callouts.",
    category: "Tech",
    style: "Dark",
    tags: ["Tech", "HUD", "Interactive"],
  },
  {
    id: "impact-83",
    name: "Heritage OS",
    description: "Luxury watch reveal with procedural floating gold particle drifts.",
    category: "Luxury",
    style: "Dark",
    tags: ["Luxury", "Particle Effects", "Cinematic"],
  },
  {
    id: "impact-84",
    name: "Flux Kitchen",
    description: "Continuous culinary drift stream with vertical parallax movement.",
    category: "Luxury",
    style: "Light",
    tags: ["Food", "Special FX", "Luxury"],
  },
  {
    id: "impact-85",
    name: "Map OS",
    description: "Interactive satellite HUD map with architectural project markers.",
    category: "Minimal",
    style: "Dark",
    tags: ["Real Estate", "HUD", "Interactive"],
  },
  {
    id: "impact-86",
    name: "Duo OS",
    description: "Photography reveal slider with chromatic duo-tone transitions.",
    category: "Luxury",
    style: "Dark",
    tags: ["Photography", "Special FX", "Editorial"],
  },
  {
    id: "impact-87",
    name: "Pure Ecom",
    description: "Immersive product showcase with high-tech HUD specs and glassmorphism UI.",
    category: "Tech",
    style: "Dark",
    tags: ["E-commerce", "Video", "HUD"],
  },
  {
    id: "impact-88",
    name: "Magnetic OS",
    description: "Interactive button grid with physics-based magnetic pull effects.",
    category: "Creative",
    style: "Dark",
    tags: ["Creative", "Interactive", "Physics"],
  },
  {
    id: "impact-89",
    name: "Matrix OS",
    description: "Massive glitched typography with procedural code fragment reveals.",
    category: "Tech",
    style: "Dark",
    tags: ["Tech", "Typography", "Interactive"],
  },
  {
    id: "impact-90",
    name: "Glitch Ed",
    description: "Structural editorial magazine with periodic procedural typography glitches.",
    category: "Editorial",
    style: "Light",
    tags: ["Editorial", "Glitch", "Magazine"],
  },
  {
    id: "impact-91",
    name: "Ritual OS",
    description: "Interactive storytelling ritual with automated protocol tracking.",
    category: "Minimal",
    style: "Light",
    tags: ["Minimal", "Storytelling", "Interactive"],
  },
  {
    id: "impact-92",
    name: "Archive 35mm",
    description: "Scrolling vertical film strip with sprocket hole aesthetics and grain overlays.",
    category: "Luxury",
    style: "Dark",
    tags: ["Photography", "Film", "Nostalgic"],
  },
  {
    id: "impact-93",
    name: "Flux OS",
    description: "Liquid displacement slider with polygon clip-path transitions.",
    category: "Creative",
    style: "Dark",
    tags: ["Slider", "Liquid", "Creative"],
  },
  {
    id: "impact-94",
    name: "Neural Mesh",
    description: "Interactive synaptic network graph with real-time connection logic.",
    category: "Tech",
    style: "Dark",
    tags: ["Tech", "Interactive", "Special FX"],
  },
  {
    id: "impact-95",
    name: "Light Ed",
    description: "Architectural light study with scroll-linked exposure and brightness shifts.",
    category: "Minimal",
    style: "Light",
    tags: ["Minimal", "Architecture", "Editorial"],
  },
  {
    id: "impact-96",
    name: "Prism OS",
    description: "Luxury jewelry reveal with refractive glassmorphism panels.",
    category: "Luxury",
    style: "Dark",
    tags: ["Luxury", "Glassmorphism", "Refractive"],
  },
  {
    id: "impact-97",
    name: "Atomic Block",
    description: "Monolithic brutalist typeface overlay with mix-blend-mode optics.",
    category: "Editorial",
    style: "Light",
    tags: ["Editorial", "Brutalist", "Typography"],
  },
  {
    id: "impact-98",
    name: "Morph OS",
    description: "Interactive grid of geometric shapes with procedural morphing logic.",
    category: "Creative",
    style: "Dark",
    tags: ["Creative", "Interactive", "SVG"],
  },
  {
    id: "impact-99",
    name: "Binary OS",
    description: "Cinematic binary rain typography with procedural logic flows.",
    category: "Tech",
    style: "Dark",
    tags: ["Tech", "Typography", "Special FX"],
  },
  {
    id: "impact-100",
    name: "Spec OS",
    description: "Stark monochromatic product spec sheet with high-contrast hardware aesthetics.",
    category: "Minimal",
    style: "Light",
    tags: ["Minimal", "Product", "Technical"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-101",
    name: "Century OS",
    description: "Memorial 100th template milestone with 3D tilted HUD and particle rain.",
    category: "Luxury",
    style: "Dark",
    tags: ["Luxury", "Tech", "3D"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-102",
    name: "Fan OS",
    description: "Interactive project card fan with radial expansion and spring physics.",
    category: "Creative",
    style: "Dark",
    tags: ["Creative", "Portfolio", "Interactive"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-103",
    name: "Sphere Ecom",
    description: "Ultra-premium glassmorphism bubble carousel for interactive products.",
    category: "Luxury",
    style: "Dark",
    tags: ["E-commerce", "Luxury", "Glassmorphism"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-104",
    name: "Maison Dorée",
    description: "Fine dining vertical menu with circular dish reveals and serif typography.",
    category: "Luxury",
    style: "Dark",
    tags: ["Food", "Menu", "Luxury"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-105",
    name: "Elysium Estates",
    description: "Cinematic real estate slider with full-bleed imagery and elegant property specs.",
    category: "Luxury",
    style: "Dark",
    tags: ["Real Estate", "Slider", "Luxury"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-106",
    name: "Studio Versa",
    description: "Warm-toned masonry portfolio with varied aspect ratios and hover reveals.",
    category: "Creative",
    style: "Light",
    tags: ["Portfolio", "Masonry", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-107",
    name: "Meridian Journey",
    description: "Immersive long-form storytelling with sticky parallax chapters and teal accents.",
    category: "Creative",
    style: "Dark",
    tags: ["Storytelling", "Parallax", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-108",
    name: "Vectral Bold",
    description: "Split diagonal hero with lime accents and bold agency typography.",
    category: "Creative",
    style: "Dark",
    tags: ["Hero", "Agency", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-109",
    name: "Lumin Gallery",
    description: "Horizontal scroll photography gallery with nature landscapes and pill labels.",
    category: "Creative",
    style: "Light",
    tags: ["Photography", "Horizontal", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-110",
    name: "Cosmo Void",
    description: "Space-themed hero with parallax mouse tracking, twinkling particles, and cyan accents.",
    category: "Tech",
    style: "Dark",
    tags: ["Space", "Hero", "Parallax"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-111",
    name: "Drop OS",
    description: "Dynamic countdown hero for product drops with fuchsia accents and live timer.",
    category: "Tech",
    style: "Dark",
    tags: ["Countdown", "Product Drop", "Tech"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-112",
    name: "Artisan Minimal",
    description: "Minimal artisan e-commerce grid with warm tones and hover cart buttons.",
    category: "Minimal",
    style: "Light",
    tags: ["E-commerce", "Minimal", "Artisan"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-113",
    name: "Nexus SaaS",
    description: "Modern SaaS one-page landing with violet accents, dashboard hero, and feature grid.",
    category: "Tech",
    style: "Dark",
    tags: ["SaaS", "Landing", "Tech"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-114",
    name: "Terra Slider",
    description: "Full-screen curtain-reveal slider with nature photography and serif titles.",
    category: "Creative",
    style: "Dark",
    tags: ["Slider", "Curtain Reveal", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-115",
    name: "Verda Parallax",
    description: "Multi-speed parallax wave gallery with emerald tones and varied image depths.",
    category: "Creative",
    style: "Dark",
    tags: ["Gallery", "Parallax", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-116",
    name: "Kyoto Teahouse",
    description: "Serene Japanese teahouse menu with washi paper tones and kanji accents.",
    category: "Luxury",
    style: "Light",
    tags: ["Food", "Japanese", "Luxury"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-117",
    name: "Stellar Carousel",
    description: "Expanding card carousel with cosmic imagery and orange accent reveals.",
    category: "Creative",
    style: "Dark",
    tags: ["Carousel", "Expanding", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-118",
    name: "Formwerk Blueprint",
    description: "Architectural blueprint hero with grid overlay, sky-blue palette, and building specs.",
    category: "Minimal",
    style: "Dark",
    tags: ["Architecture", "Blueprint", "Minimal"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-119",
    name: "IronX Fitness",
    description: "High-energy fitness grid with red accents, grayscale reveals, and bold typography.",
    category: "Creative",
    style: "Dark",
    tags: ["Fitness", "Grid", "Vibrant"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-120",
    name: "Éclat Perfume",
    description: "Luxury perfume scroll reveal with deep plum tones, expanding rings, and editorial serif.",
    category: "Luxury",
    style: "Dark",
    tags: ["Beauty", "Luxury", "Scroll Reveal"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-121",
    name: "Folio studio",
    description: "Mousetrap portfolio list with floating preview images that follow cursor.",
    category: "Creative",
    style: "Light",
    tags: ["Portfolio", "Mousetrap", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-122",
    name: "Chronicle Story",
    description: "Long-form editorial scroll story with full-bleed images and large serif prose.",
    category: "Editorial",
    style: "Light",
    tags: ["Editorial", "Storytelling", "Long Read"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-123",
    name: "Maison Fashion",
    description: "Fashion editorial split-screen with lookbook images and yellow accent CTA.",
    category: "Luxury",
    style: "Dark",
    tags: ["Fashion", "Editorial", "Split"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-124",
    name: "Morph Studio",
    description: "Fluid morphing hero with scroll-linked border-radius transition from circle to full-bleed.",
    category: "Creative",
    style: "Light",
    tags: ["Hero", "Morphing", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-125",
    name: "Aura Interactive",
    description: "Custom cursor trail hero with large amber circle, mix-blend-difference, and abstract bg.",
    category: "Creative",
    style: "Dark",
    tags: ["Hero", "Interactive", "Cursor"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-126",
    name: "Trattoria Menu",
    description: "Italian restaurant tabbed menu with warm leather tones and orange accents.",
    category: "Luxury",
    style: "Dark",
    tags: ["Food", "Menu", "Italian"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-127",
    name: "Pulse Events",
    description: "Neon concert/festival hero with pink glow effects and live event indicators.",
    category: "Creative",
    style: "Dark",
    tags: ["Events", "Neon", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-128",
    name: "Haven Real Estate",
    description: "Warm-toned real estate card grid with property specs and price pills.",
    category: "Minimal",
    style: "Light",
    tags: ["Real Estate", "Grid", "Minimal"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-129",
    name: "Wave FX",
    description: "Real-time canvas particle wave system with mouse interaction and indigo palette.",
    category: "Tech",
    style: "Dark",
    tags: ["Tech", "Canvas", "Particles"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-130",
    name: "Split Reveal",
    description: "Split-screen slider with left image and right content, emerald accents.",
    category: "Creative",
    style: "Dark",
    tags: ["Slider", "Split", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-131",
    name: "Cuvée Prestige",
    description: "Wine showcase hero with deep burgundy tones, vineyard backdrop, and bottle presentation.",
    category: "Luxury",
    style: "Dark",
    tags: ["Wine", "Luxury", "Showcase"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-132",
    name: "Elementum",
    description: "Clean alternating-row portfolio with nature imagery and ultra-light typography.",
    category: "Minimal",
    style: "Light",
    tags: ["Portfolio", "Alternating", "Minimal"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-133",
    name: "Atlas Zoom",
    description: "Dramatic zoom-out reveal hero with city skyline and sky-blue accents.",
    category: "Creative",
    style: "Dark",
    tags: ["Hero", "Zoom", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-134",
    name: "Lumière Beauty",
    description: "Beauty/skincare e-commerce grid with peach tones and rose accent tags.",
    category: "Luxury",
    style: "Light",
    tags: ["Beauty", "E-commerce", "Luxury"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-135",
    name: "Trade OS",
    description: "Live stock ticker dashboard with dynamic data updates, green/red indicators.",
    category: "Tech",
    style: "Dark",
    tags: ["Fintech", "Dashboard", "Tech"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-136",
    name: "Text Reveal",
    description: "Text mask scroll reveal where background image expands through scroll-linked inset clip-path.",
    category: "Creative",
    style: "Dark",
    tags: ["Scroll Reveal", "Text Mask", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-137",
    name: "Torréfié Coffee",
    description: "Specialty coffee roaster one-page with warm paper tones and origin card grid.",
    category: "Minimal",
    style: "Light",
    tags: ["Coffee", "One-Page", "Minimal"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-138",
    name: "Prism Analytics",
    description: "Glassmorphism analytics dashboard with gradient background, bar chart, and metric cards.",
    category: "Tech",
    style: "Dark",
    tags: ["Analytics", "Dashboard", "Tech"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-139",
    name: "Apex Automotive",
    description: "Automotive hero with luxury car backdrop, performance specs, and red CTA.",
    category: "Luxury",
    style: "Dark",
    tags: ["Automotive", "Luxury", "Hero"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-140",
    name: "Wanderlust",
    description: "Travel agency hero with destination cards, amber accents, and full-bleed landscape.",
    category: "Minimal",
    style: "Dark",
    tags: ["Travel", "Hero", "Minimal"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-141",
    name: "Sonic Player",
    description: "Music player hero with album art, progress bar, and purple glow effects.",
    category: "Creative",
    style: "Dark",
    tags: ["Music", "Player", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-142",
    name: "Verdant Impact",
    description: "Sustainability/green tech one-page with forest imagery and impact metrics.",
    category: "Minimal",
    style: "Light",
    tags: ["Sustainability", "Eco", "Minimal"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-143",
    name: "Atelier Interior",
    description: "Interior design slider with full-screen room photography and elegant dot navigation.",
    category: "Luxury",
    style: "Light",
    tags: ["Interior", "Slider", "Luxury"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-144",
    name: "Kinetic Marquee",
    description: "Kinetic typography with dual opposing scroll-linked marquee bands and orange accent.",
    category: "Creative",
    style: "Dark",
    tags: ["Typography", "Marquee", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-145",
    name: "Deepcast",
    description: "Podcast landing with episode list, play buttons, and yellow accent on deep navy.",
    category: "Creative",
    style: "Dark",
    tags: ["Podcast", "Landing", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-146",
    name: "Velos FinTech",
    description: "Sleek crypto wallet landing with glassmorphism dashboard, cyan accents, and asset metrics.",
    category: "Tech",
    style: "Dark",
    tags: ["FinTech", "Crypto", "Glassmorphism"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-147",
    name: "Void Arch",
    description: "Minimalist Black & White architecture portfolio with staggered layout and grayscale-to-color reveals.",
    category: "Minimal",
    style: "Light",
    tags: ["Architecture", "Portfolio", "B&W"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-148",
    name: "Pureté Skincare",
    description: "Organic skincare storytelling with soft cream tones, delicate serif typography, and botanical atmosphere.",
    category: "Luxury",
    style: "Light",
    tags: ["Skincare", "Storytelling", "Luxury"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-149",
    name: "Nørdic Furniture",
    description: "High-end furniture showcase with 3D perspective transitions and bold italic typography.",
    category: "Luxury",
    style: "Dark",
    tags: ["Furniture", "3D", "Premium"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-150",
    name: "Neon Unit Apparel",
    description: "Cyberpunk-themed apparel shop with neon cyan accents, glitch aesthetic, and technical data overlays.",
    category: "Tech",
    style: "Dark",
    tags: ["Cyberpunk", "Apparel", "E-commerce"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-151",
    name: "Chronos Lab",
    description: "Luxury watch technical detail page with scroll-linked zoom, HUD-inspired overlays, and bold italic typography.",
    category: "Luxury",
    style: "Dark",
    tags: ["Watch", "Technical", "Luxury"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-152",
    name: "Wanderer Mag",
    description: "Elegant travel magazine layout with high-impact editorial typography, large-scale imagery, and minimalist serif aesthetics.",
    category: "Editorial",
    style: "Light",
    tags: ["Magazine", "Travel", "Editorial"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-153",
    name: "Véloce Team",
    description: "High-tech startup team grid with interactive grayscale-to-color hover states, animated bio reveals, and sleek dark mode aesthetics.",
    category: "Tech",
    style: "Dark",
    tags: ["Team", "Startup", "Interactive"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-154",
    name: "Obliq Services",
    description: "Dynamic creative agency services layout with full-bleed parallax images, diagonal energy, and high-impact italic typography.",
    category: "Creative",
    style: "Dark",
    tags: ["Agency", "Services", "Creative"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-155",
    name: "Art Index",
    description: "Modern digital art gallery with cinematic scroll-linked cross-fades, perspective shifts, and bold heroic typography.",
    category: "Creative",
    style: "Dark",
    tags: ["Art", "Gallery", "Scroll Reveal"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-156",
    name: "Bio Form Arch",
    description: "Sustainable architecture one-page landing with a natural sage palette, bold italic typography, and impact-focused project cards.",
    category: "Minimal",
    style: "Light",
    tags: ["Sustainability", "Architecture", "Minimal"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-157",
    name: "Aurum Jewelry",
    description: "Ultra-premium jewelry e-commerce detail page with deep obsidian tones, gold accents, and a focus on high-end sculptural photography.",
    category: "Luxury",
    style: "Dark",
    tags: ["Jewelry", "E-commerce", "Luxury"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-158",
    name: "Proto Log",
    description: "Aggressive neo-brutalist editorial layout with thick black borders, stark monochromatic typography, and high-impact hover effects.",
    category: "Editorial",
    style: "Light",
    tags: ["Brutalist", "Editorial", "News"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-159",
    name: "Re Con Tech",
    description: "High-energy tech event landing with dynamic countdown, neon gradient accents, and immersive particle-style background effects.",
    category: "Tech",
    style: "Dark",
    tags: ["Event", "Tech", "Countdown"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-160",
    name: "Maison V Lookbook",
    description: "Minimalist staggered fashion lookbook with high-contrast monochrome design, hover effects, and bold heroic headings.",
    category: "Minimal",
    style: "Light",
    tags: ["Fashion", "Lookbook", "Minimal"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-161",
    name: "Essential SaaS",
    description: "Clean SaaS Landing Page with WordPress/Elementor-ready semantic HTML block structure.",
    category: "Free",
    style: "Light",
    tags: ["SaaS", "Landing", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-162",
    name: "Essential Cafe",
    description: "Local Cafe theme with warm colors, classic layout, and direct WordPress container mapping.",
    category: "Free",
    style: "Light",
    tags: ["Local Business", "Food", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-163",
    name: "Essential Blog",
    description: "Clean Personal Blog layout with sidebar, classic typography, and WordPress-ready structure.",
    category: "Free",
    style: "Light",
    tags: ["Blog", "Personal", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-164",
    name: "Essential Agency",
    description: "Minimalist B&W Agency layout, strictly structured for easy WordPress conversion.",
    category: "Free",
    style: "Dark",
    tags: ["Agency", "Portfolio", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-165",
    name: "Essential App",
    description: "App Promo landing page with simple device mockup and bright, clean UI structure.",
    category: "Free",
    style: "Light",
    tags: ["App", "Promo", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-166",
    name: "Essential Photography",
    description: "Clean dark-mode Photography Portfolio using CSS columns for an easy Masonry grid.",
    category: "Free",
    style: "Dark",
    tags: ["Photography", "Portfolio", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-167",
    name: "Essential Real Estate",
    description: "Clean Real Estate listing block with search hero element, standard flex/grid usage.",
    category: "Free",
    style: "Light",
    tags: ["Real Estate", "Listing", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-168",
    name: "Essential E-Commerce",
    description: "Minimalist E-Commerce layout with hero banner and standard product grid.",
    category: "Free",
    style: "Light",
    tags: ["E-commerce", "Shop", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-169",
    name: "Essential Newsletter",
    description: "Newsletter signup landing page, highly conversion-focused with elegant typography.",
    category: "Free",
    style: "Light",
    tags: ["Newsletter", "Landing", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-170",
    name: "Essential CV",
    description: "Consultant CV/Resume layout with solid structural hierarchy and clean sidebar.",
    category: "Free",
    style: "Light",
    tags: ["CV", "Resume", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-171",
    name: "Essential Medical",
    description: "Medical/Clinic layout with trust-building elements, emergency banner, and service grids.",
    category: "Free",
    style: "Light",
    tags: ["Medical", "Health", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-172",
    name: "Essential Law Firm",
    description: "Law Firm structure with serif typography, elegant sections, and trust-focused layout.",
    category: "Free",
    style: "Light",
    tags: ["Law", "Corporate", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-173",
    name: "Essential Construction",
    description: "Construction/Contractor layout with bold, industrial aesthetic and yellow accents.",
    category: "Free",
    style: "Dark",
    tags: ["Construction", "Industrial", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-174",
    name: "Essential Fitness",
    description: "High-energy Fitness/Gym layout with dark styling, cyan highlights, and bold typography.",
    category: "Free",
    style: "Dark",
    tags: ["Fitness", "Gym", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-175",
    name: "Essential Event",
    description: "Event/Conference landing page with vibrant colors, simple speaker grid, and clear CTA.",
    category: "Free",
    style: "Vibrant",
    tags: ["Event", "Conference", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-176",
    name: "Essential Dashboard",
    description: "Clean SaaS Admin dashboard structure using native CSS grids and simple UI components.",
    category: "Free",
    style: "Light",
    tags: ["Dashboard", "SaaS", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-177",
    name: "Essential Podcast",
    description: "Tech Podcast landing page with elegant dark mode, audio player hints, and list block.",
    category: "Free",
    style: "Dark",
    tags: ["Podcast", "Media", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-178",
    name: "Essential Cleaning",
    description: "Light and Trustworthy Cleaning Service landing page with review badges and ZIP code form.",
    category: "Free",
    style: "Light",
    tags: ["Service", "Local Business", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-179",
    name: "Essential Non-profit",
    description: "Non-profit charity landing page with emotional photography, serif headers, and donation CTA.",
    category: "Free",
    style: "Light",
    tags: ["Charity", "Non-profit", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-180",
    name: "Essential Salon",
    description: "Premium Barber/Salon split-screen layout with dark aesthetic and price list.",
    category: "Free",
    style: "Dark",
    tags: ["Salon", "Barber", "Free"],
    tier: "Essentiel",
    sections: 7,
  },
  {
    id: "impact-181",
    name: "Nexus Web3",
    description: "Premium Web3/Crypto landing page with floating ORB backgrounds, glassmorphism UI, and fluid animations.",
    category: "Tech",
    style: "Vibrant",
    tags: ["Web3", "Crypto", "DeFi"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-182",
    name: "The Grand Hotel",
    description: "Premium Luxury Hotel landing page with elegant serif fonts, parallax feels, and large immersive photography.",
    category: "Luxury",
    style: "Light",
    tags: ["Hotel", "Travel", "Elegant"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-183",
    name: "Cognix AI",
    description: "Premium AI SaaS Platform featuring neumorphic glass impacts, dark mode glows, and generative interface hints.",
    category: "Tech",
    style: "Dark",
    tags: ["AI", "SaaS", "Dashboard"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-184",
    name: "MoMA Structure",
    description: "Premium Modern Museum with Brutalist sidebar layout, extreme typography and solid borders.",
    category: "Creative",
    style: "Light",
    tags: ["Museum", "Art", "Brutalist"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-185",
    name: "Velma Editorial",
    description: "Premium Fashion Brand layout featuring massive hero text blending with background photography.",
    category: "Editorial",
    style: "Light",
    tags: ["Fashion", "Lookbook", "Oversized Text"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-186",
    name: "ArchiTectura",
    description: "Premium Architecture firm structural grid with brutalist grayscale hover reveals.",
    category: "Minimal",
    style: "Dark",
    tags: ["Architecture", "Studio", "Grayscale"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-187",
    name: "Vault FinTech",
    description: "Premium FinTech Interface with glowing charts, deep blue/emerald gradients, and glassmorphism.",
    category: "Tech",
    style: "Dark",
    tags: ["FinTech", "App", "Gradients"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-188",
    name: "Cinema Roster",
    description: "Premium Film Production horizontal-scroll aesthetic with cinematic typography and giant cinematic tiles.",
    category: "Creative",
    style: "Dark",
    tags: ["Film", "Production", "Horizontal Scroll"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-189",
    name: "Aura Dining",
    description: "Premium Restaurant/Dining layout with dark romantic themes, elegant thin serifs, and tall image masks.",
    category: "Luxury",
    style: "Dark",
    tags: ["Restaurant", "Dining", "Romantic"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-190",
    name: "Nexus Gaming",
    description: "Premium Cyberpunk/Gaming Studio landing page with neon grid effects, glitch-inspired text, and stark lines.",
    category: "Tech",
    style: "Dark",
    tags: ["Gaming", "Cyberpunk", "Neon"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-191",
    name: "Premium Interior",
    description: "Elegant interior design showcase with minimalist layouts and smooth scroll transitions.",
    category: "Luxury",
    style: "Light",
    tags: ["Interior", "Architecture", "Minimal"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-192",
    name: "Premium Fragrance",
    description: "High-end perfume landing page with cinematic parallax and deep ambient aesthetics.",
    category: "Luxury",
    style: "Dark",
    tags: ["Fragrance", "Luxury", "Parallax"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-193",
    name: "Premium Festival",
    description: "Dynamic event experience with vibrant colors, kinetic typography, and fluid schedules.",
    category: "Creative",
    style: "Vibrant",
    tags: ["Event", "Festival", "Vibrant"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-194",
    name: "Premium Web Agency",
    description: "Modern creative studio showcase with bold grid layouts and technical details.",
    category: "Creative",
    style: "Dark",
    tags: ["Agency", "Portfolio", "Grid"],
    tier: "Premium",
    sections: 15,
  },
  {
    id: "impact-195",
    name: "Premium Bakery",
    description: "Artisanal food experience with elegant serif typography and warm atmospheric lighting.",
    category: "Luxury",
    style: "Light",
    tags: ["Food", "Bakery", "Artisanal"],
    tier: "Premium",
    sections: 15,
  },
];
